name: Sync README

on:
  push:
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install regex
    - name: Run sync script
      run: python sync_readme.py
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.ua.md
        git commit -m 'Synchronize README.ua.md with README.md'
        git push
